//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.Tafe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tafe.ReverseSoap")]
    public interface ReverseSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reversed", ReplyAction="*")]
        ServiceTest.Tafe.ReversedResponse Reversed(ServiceTest.Tafe.ReversedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reversed", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.Tafe.ReversedResponse> ReversedAsync(ServiceTest.Tafe.ReversedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reversed", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.Tafe.ReversedRequestBody Body;
        
        public ReversedRequest() {
        }
        
        public ReversedRequest(ServiceTest.Tafe.ReversedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReversedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ReversedRequestBody() {
        }
        
        public ReversedRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.Tafe.ReversedResponseBody Body;
        
        public ReversedResponse() {
        }
        
        public ReversedResponse(ServiceTest.Tafe.ReversedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReversedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReversedResult;
        
        public ReversedResponseBody() {
        }
        
        public ReversedResponseBody(string ReversedResult) {
            this.ReversedResult = ReversedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReverseSoapChannel : ServiceTest.Tafe.ReverseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReverseSoapClient : System.ServiceModel.ClientBase<ServiceTest.Tafe.ReverseSoap>, ServiceTest.Tafe.ReverseSoap {
        
        public ReverseSoapClient() {
        }
        
        public ReverseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReverseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.Tafe.ReversedResponse ServiceTest.Tafe.ReverseSoap.Reversed(ServiceTest.Tafe.ReversedRequest request) {
            return base.Channel.Reversed(request);
        }
        
        public string Reversed(string input) {
            ServiceTest.Tafe.ReversedRequest inValue = new ServiceTest.Tafe.ReversedRequest();
            inValue.Body = new ServiceTest.Tafe.ReversedRequestBody();
            inValue.Body.input = input;
            ServiceTest.Tafe.ReversedResponse retVal = ((ServiceTest.Tafe.ReverseSoap)(this)).Reversed(inValue);
            return retVal.Body.ReversedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.Tafe.ReversedResponse> ServiceTest.Tafe.ReverseSoap.ReversedAsync(ServiceTest.Tafe.ReversedRequest request) {
            return base.Channel.ReversedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.Tafe.ReversedResponse> ReversedAsync(string input) {
            ServiceTest.Tafe.ReversedRequest inValue = new ServiceTest.Tafe.ReversedRequest();
            inValue.Body = new ServiceTest.Tafe.ReversedRequestBody();
            inValue.Body.input = input;
            return ((ServiceTest.Tafe.ReverseSoap)(this)).ReversedAsync(inValue);
        }
    }
}
